[package]
edition = "2018"
name = "ra_syntax"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Comment and whitespace preserving parser for the Rust langauge"
repository = "https://github.com/rust-analyzer/rust-analyzer"

[dependencies]
arrayvec = "0.4.10"
unicode-xid = "0.1.0"
itertools = "0.8.0"
drop_bomb = "0.1.4"
parking_lot = "0.7.0"
rowan = "0.2.0"
text_unit = "0.1.5"
ra_text_edit = { path = "../ra_text_edit" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
walkdir = "2.2.0"
